services:
  - type: web
    name: ai-studyplanner
    runtime: docker
    repo: https://github.com/abhuvana17/ai_studyplanner
    context: .
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: POE_API_KEY
        sync: false
